#image: allentpg/djangotest
image: docker/compose:latest
stages:
  - test
  - deploy

docker-deploy:
  stage: deploy
  # 执行Job内容
  script:
    #- docker-compose down
    #- docker rmi cicd-demo
    # 通过Dockerfile生成cicd-demo镜像
    #- docker build -t cicd-demo .
    #- docker rmi $(docker images -f "dangling=true" -q) 1>/dev/null 2>&1 | exit 0
    # 删除已经在运行的容器
    #- if [ $(docker ps -aq --filter name= cicd-demo) ]; then docker rm -f cicd-demo;fi

    - docker-compose up -d
  tags:
    # 执行Job的服务器
    - macrunner
  only:
    # 只有在master分支才会执行
    - master

test:
    stage: test
    script:
        - docker stop test || true && docker rm test || true
        - docker stop waferroll || true && docker rm waferroll || true
        - docker rmi allentpg/waferroll || true
        - docker build -t allentpg/waferroll .
        - docker login --username allentpg --password Summer2019
        - docker push allentpg/waferroll
        - docker run --name test allentpg/waferroll /bin/bash -c "python3 manage.py test"
    tags:
        - macrunner

