# Generated by Django 3.0.3 on 2020-04-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=16, unique=True, verbose_name='Site ID')),
                ('site_name', models.CharField(max_length=64, unique=True, verbose_name='Site Name')),
                ('site_lat', models.FloatField(verbose_name='Latitude')),
                ('site_long', models.FloatField(verbose_name='Longitude')),
                ('site_cluster', models.CharField(max_length=64, verbose_name='Cluster')),
                ('site_state', models.CharField(max_length=32, verbose_name='State')),
                ('site_pole_owner', models.CharField(max_length=64, verbose_name='Pole Owner')),
                ('site_pole_id', models.CharField(max_length=64, unique=True, verbose_name='Pole ID')),
                ('site_rfnsa_id', models.CharField(max_length=12, null=True, unique=True, verbose_name='RFNSA ID')),
                ('site_acma_id', models.CharField(max_length=12, null=True, unique=True, verbose_name='ACMA ID')),
                ('site_status', models.SmallIntegerField(choices=[(1, 'MSL Completed'), (2, 'Cluster Finalization Completed'), (3, 'Site Survey Completed'), (4, 'Site Survey Review Completed'), (5, 'STAD Lockdown Completed'), (6, 'DC6 Consultation Completed'), (7, 'Site Construction Completed'), (8, 'Site Integration and RFI Completed'), (9, 'Regulatory Fulfillment Completed'), (10, 'SSV Completed')], default=1, verbose_name='Current Status')),
                ('site_last_end_date', models.DateField(null=True, verbose_name='Last milestone date')),
            ],
            options={
                'verbose_name': 'SiteBasicData',
                'verbose_name_plural': 'SiteBasicData',
                'db_table': 'site_basic',
                'ordering': ['site_id'],
            },
        ),
    ]
